twig:
    paths:
        '%kernel.project_dir%/templates': default
        '%kernel.project_dir%/packages/kopyl-solution/AdminBundle/templates': admin_bundle
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
